const ACTION_TYPES = {
  // ACCOUNT
  EDIT_ACCOUNT: 'EDIT_ACCOUNT',


  // AUTH
  LOG_IN:  'LOG_IN',
  LOG_OUT: 'LOG_OUT',


  // NEWS

  // Post
  SET_CURRENT_POST:  'SET_CURRENT_POST',
  EDIT_CURRENT_POST: 'EDIT_CURRENT_POST',

  // Blog
  SET_POSTS:      'SET_POSTS',
  SET_CATEGORIES: 'SET_CATEGORIES',
};

export default ACTION_TYPES;
